"use client";

import { useEffect, useMemo, useRef, useState } from "react";
import { createAvatar } from "@dicebear/core";
import { personas } from "@dicebear/collection";

/**
 * Mitul's avatar — generated by DiceBear's `personas` style.
 *
 * Hand-coded portraits weren't working. DiceBear's personas style is a
 * professionally-designed illustrated avatar set; we configure the
 * options so the result reads as Mitul (dark wavy hair, full beard with
 * mustache, navy blazer, friendly smile, warm skin tone).
 *
 * The SVG is generated once at mount via `createAvatar(...).toString()`
 * and injected with `dangerouslySetInnerHTML` (DiceBear output is sanitized).
 *
 * Layered effects on top of the base avatar:
 *   - Soft primary-color radial spotlight halo behind the avatar
 *   - Breathing scale animation (1.006 / 8s, paused off-screen)
 *   - IntersectionObserver to disable motion when not visible
 */
export function EditorialPortrait() {
  const wrapRef = useRef<HTMLDivElement | null>(null);
  const [visible, setVisible] = useState(true);

  const svgString = useMemo(() => {
    const avatar = createAvatar(personas, {
      seed: "mitul-jagad",
      backgroundColor: ["transparent"],
      // Hair: textured wavy short style. Personas only ships a fixed set;
      // shortCombover + curly together let the seed pick whichever lands.
      hair: ["shortCombover"],
      hairColor: ["362c47"],
      // Full beard with mustache — closest to Mitul's reference photo.
      facialHair: ["beardMustache"],
      facialHairProbability: 100,
      // Friendly smile + open eyes
      mouth: ["smile"],
      eyes: ["open"],
      nose: ["mediumRound"],
      // Squared body = blazer silhouette
      body: ["squared"],
      skinColor: ["b16a5b"],
      clothingColor: ["1f3a5f"], // navy blazer
      size: 400,
      radius: 0,
    });
    return avatar.toString();
  }, []);

  useEffect(() => {
    if (!wrapRef.current) return;
    const io = new IntersectionObserver(
      (entries) => {
        for (const e of entries) setVisible(e.isIntersecting);
      },
      { threshold: 0.1 },
    );
    io.observe(wrapRef.current);
    return () => io.disconnect();
  }, []);

  return (
    <div
      ref={wrapRef}
      className="absolute inset-0 grid place-items-center overflow-hidden"
    >
      {/* Soft primary-color spotlight halo — adapts to every theme */}
      <div
        aria-hidden="true"
        className="absolute inset-0 pointer-events-none"
        style={{
          background:
            "radial-gradient(ellipse 60% 55% at 50% 40%, color-mix(in srgb, var(--primary) 28%, transparent) 0%, transparent 70%)",
        }}
      />

      {/* The avatar itself — breathes gently when visible */}
      <div
        className={`relative z-10 w-[88%] h-[88%] grid place-items-center ${visible ? "portrait-breathing" : ""}`}
        // DiceBear's createAvatar outputs a clean SVG string. The library
        // owns the markup and the project's lint config trusts it.
        dangerouslySetInnerHTML={{ __html: svgString }}
      />
    </div>
  );
}
